[[main]]
URL = "/about/"
name = "About"
weight = 1

[[main]]
URL = "/contact/"
name = "Contact"
weight = 2

[[main]]
URL = "/blog/"
name = "Blog"
weight = 3

[[main]]
URL = "/free-case-study/"
name = "FREE Case Study"
weight = 4