home = "Home"
phone = "‭+44 7561399765‬"
email = "contact@adamfaryna.com"
author = "Adam Faryna"
owner = "Appdy"
title = "Adam Faryna"
description = "Digital Marketing Consultant"
startYear = "2016-01-01"
URI = "adamfaryna.com"

# gtag = "GTM-WVDXKLS"
google_analytics_id = ""
facebook_id = ""
# copyright = "© Copyright 2016-2020 AdamFaryna.com"

# preloader
[preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

[[footer.links]]
label = "Privacy Policy"
URL = "privacy-policy"

[[footer.links]]
label = "Cookie Policy"
URL = "cookie-policy"

[[footer.links]]
label = "Terms Of Service"
URL = "terms-of-service"


# preconnect
[[preconnect]]
link = "https://ssl.gstatic.com"

[[preconnect]]
link = "https://www.gstatic.com"

[[preconnect]]
link = "https://fonts.googleapis.com"


# preloads
[[preload]]
link = "/fonts/nunito/Nunito-Bold.woff2"
as = "font"

[[preload]]
link = "/fonts/nunito/Nunito-ExtraBold.woff2"
as = "font"

[[preload]]
link = "/fonts/poppins/Poppins-Medium.woff2"
as = "font"

[[preload]]
link = "/fonts/poppins/Poppins-Light.woff2"
as = "font"

[[preload]]
link = "/fonts/nunito/Nunito-SemiBold.woff2"
as = "font"

[[preload]]
link = "/fonts/poppins/Poppins-Bold.woff2"
as = "font"

[[preload]]
link = "/webfonts/fa-brands-400.woff2"
as = "font"

[[preload]]
link = "/fonts/poppins/Poppins-Regular.woff2"
as = "font"

[[preload]]
link = "/webfonts/fa-solid-900.woff2"
as = "font"


# JS assets
[[assets.js]]
link = "js/script.js"
async = true
